---
# Collects diagnostic information for the currently running cord-pod config

- name: Create diag_dir fact
  hosts: head
  tasks:
    - set_fact:
        diag_dir: "diag-{{ ansible_date_time.iso8601_basic_short }}"

- name: Diagnostics on head node
  hosts: head
  roles:
    - head-diag

- name: Diagnostics on compute nodes
  hosts: compute
  roles:
    - compute-diag

- name: Collect compute node diagnostics on head node
  hosts: compute
  tasks:
    - synchronize:
        src: "/tmp/{{ hostvars[groups['head'][0]]['diag_dir'] }}/{{ inventory_hostname }}"
        dest: "~/{{ hostvars[groups['head'][0]]['diag_dir'] }}/"
        recursive: yes
        mode: pull
      delegate_to: "{{ groups['head'][0] }}"

