---
# onos-vm-install/tasks/main.yml
#
# Install ONOS on a sub vm by calling ansible

- name: Create a vars file from template
  template:
    src=onos-setup-vars.yml.j2
    dest={{ ansible_user_dir }}/onos-setup-vars.yml

- name: Copy over ONOS playbook and docker compose files
  copy:
    src={{ item }}
    dest={{ ansible_user_dir }}/{{ item }}
  with_items:
    - onos-setup-playbook.yml
    - onos-docker-compose.yml
    - fabric-docker-compose.yml
    - Dockerfile.xos-onos
    - onos-service

- name: Run the ONOS ansible playbook
  command: ansible-playbook {{ ansible_user_dir }}/onos-setup-playbook.yml
  async: 1200
  poll: 0
  register: onos_setup_playbook

