---

xos_repo_url: "https://github.com/girishgc/xos.git"
xos_repo_dest: "~/xos"
xos_repo_branch: "HEAD"

xos_configuration: "devel"

xos_container_rebuild: false

service_profile_repo_url: "https://github.com/girishgc/service-profile.git"
service_profile_repo_dest: "~/service-profile"
service_profile_repo_branch: "HEAD"
