---
- shell: uvt-kvm ip juju
  register: juju_ip

- shell: uvt-kvm ip mysql
  register: mysql_ip

- shell: uvt-kvm ip rabbitmq-server
  register: rabbitmq_ip

- shell: uvt-kvm ip keystone
  register: keystone_ip

- shell: uvt-kvm ip glance
  register: glance_ip

- shell: uvt-kvm ip nova-cloud-controller
  register: novacc_ip

- shell: uvt-kvm ip neutron-gateway
  register: neutron_ip

- shell: uvt-kvm ip openstack-dashboard
  register: horizon_ip

- shell: uvt-kvm ip nagios
  register: nagios_ip

- shell: uvt-kvm ip ceilometer
  register: ceilometer_ip

- shell: uvt-kvm ip neutron-api
  register: neutron_api_ip
